% =========================================================================
% closureErrors2D.m
% =========================================================================
% Author:        Benjamin B Bolduc
% Last Updated:  March 2026
%
% Description: 
%   Evaluates given joint angles generated by the numerical solver and 
%   computes the solver's residuals. Three constraints are imposed:
%   1. Loop closure: The parts must form closed loops (X and Y vector sums = 0)
%   2. Ground constraint: The first body must remain horizontal (angle = 0)
%   3. Input constraint: The input joints must match the given user parameters
% =========================================================================

function Eqs = closureErrors2D(x0, mechanism, thetaInputs, mode, movingIndices, nBodies)
    
    %% ====================================================================
    % ASSEMBLING THE ARRAY
    % ====================================================================
    % fsolve only gives us the angles of the moving bodies (x0). We must 
    % rebuild the complete list of angles (Phi_all) by hardcoding the first 
    % body back to 0 degrees at the very top.
    
    Phi_all = zeros(nBodies, 1);
    numMovingBodies = numel(movingIndices); % Count how many bodies are moving
    
    % Use a simple loop to slot the moving guesses into their array positions
    for i = 1:numMovingBodies
        bodyID = movingIndices(i);
        Phi_all(bodyID) = x0(i);
    end
    
    Eqs = []; % Initialize the list of errors
    
    %% ====================================================================
    % CONSTRAINT 1: LOOP CLOSURE
    % ====================================================================
    % Take the unrotated lengths of the bodies, rotate them by their 
    % absolute angles found in Phi_all, and add them together. If the 
    % kinematic chain is properly closed, the total X and Y loop vector will
    % be exactly zero.
    
    for k = 1:numel(mechanism.loops)
        loop = mechanism.loops(k);
        bodyIndices = loop.bodyIndices; 
        vectors = loop.vectors;    
        
        sum_x = 0; 
        sum_y = 0;
        
        for i = 1:numel(bodyIndices)
            bIdx = bodyIndices(i);
            val = Phi_all(bIdx);
            v_local = vectors(:, i);

            if loop.isPrismatic(i)
                phi = 0; % A sliding body does not rotate
                
                % Find which way the slider track is pointing
                mag = norm(v_local);
                if mag > 1e-9
                    unit_v = v_local / mag;
                else
                    unit_v = [1; 0; 0]; 
                end
                
                % Stretch the vector by the linear sliding amount
                v_final = v_local + val * unit_v; 
            else
                phi = val;
                v_final = v_local;
            end
            
            % 2D Rotation Matrix to find the actual X and Y span
            c = cos(phi); 
            s = sin(phi);
            v_x = c * v_final(1) - s * v_final(2);
            v_y = s * v_final(1) + c * v_final(2);
            
            % Accumulate the total distance traveled along the loop
            sum_x = sum_x + v_x;
            sum_y = sum_y + v_y;
        end
        
        % Stack the X gap and Y gap for this loop into the master error list
        Eqs = [Eqs; sum_x; sum_y];
    end
    
    %% ====================================================================
    % RULE 2: GROUND CONSTRAINT
    % =====================================================================    
    frameIdx = 1; 
    Eqs = [Eqs; Phi_all(frameIdx)]; 
    
    %% ====================================================================
    % CONSTRAINT 3: USER INPUT CONSTRAINT
    % ====================================================================
    % Ensure the solver respects the user's input parameters. We subtract 
    % the absolute angles of the two bodies connected to the driven joint, 
    % and measure how far that difference is from the user's requested angle.
    
    inputLabels = fieldnames(thetaInputs);
    
    for i = 1:numel(inputLabels)
        label = inputLabels{i};
        theta_desired = thetaInputs.(label);
        
        % Search for the driven joint(s) in the JSON data
        jIdx = 0;
        for j = 1:numel(mechanism.joints)
            if iscell(mechanism.joints)
                jnt = mechanism.joints{j}; 
            else
                jnt = mechanism.joints(j); 
            end

            if strcmp(jnt.label, label)
                jIdx = j;
                joint = jnt;
                break;
            end
        end
        
        if jIdx == 0
            error('SOLVER ERROR: The input "%s" was not found in the JSON.', label);
        end
        
        % Take absolute global angles of the two bodies attached to the input joint
        idxA = find(strcmp({mechanism.bodies.name}, joint.bodies{1}));
        idxB = find(strcmp({mechanism.bodies.name}, joint.bodies{2}));
        phi_a = Phi_all(idxA);
        phi_b = Phi_all(idxB);
        
        % Error = (Actual joint angle) - (Desired input angle)
        diff = phi_b - phi_a - theta_desired;
        
        % Wrap the error to keep it between -pi and +pi so fsolve doesn't get confused
        if strcmp(mode, 'atan2')
            angle_err = atan2(sin(diff), cos(diff)); 
        else
            angle_err = diff;
        end
        
        % Stack the motor error into the master list
        Eqs = [Eqs; angle_err];
    end
end